######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 5 20:19:42 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += obstacle_map.h skifall.h skifall_canvas.h
SOURCES += main.cpp obstacle_map.cpp skifall.cpp skifall_canvas.cpp
